[package]
name = "bueller"
version = "0.0.0"
authors = ["Peter Wildani <pabw00@gmail.com>"]

[dependencies]
time = "0.1"
slab = "0.1.0"

[dependencies.mio]
git = "https://github.com/carllerche/mio/"

[dependencies.url]
# Currently also provides idna
git = "https://github.com/servo/rust-url"

