[package]
name = "bueller"
version = "0.0.0"
authors = ["Peter Wildani <pabw00@gmail.com>"]

[dependencies]
#mio = "0.4.1"

[dependencies.mio]
git = "https://github.com/carllerche/mio/"
rev = "15b05993bd0761ddf7a1a22396d545908dd3a0a3"

[dependencies.url]
git = "https://github.com/servo/rust-url"
